name: Docs

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy MkDocs to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for mkdocs-git-revision-date-localized

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install MkDocs dependencies
        run: |
          pip install mkdocs-material mkdocstrings[python] pymdown-extensions

      - name: Deploy docs
        run: mkdocs gh-deploy --force
